baseURL = "https://ingridksv.github.io/portfolio/"
title = "Ingrid Karen Svendsen"
theme = "hextra"
defaultContentLanguage = "da"

enableRobotsTXT = true
enableEmoji = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
