disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Ingrid Karen Svendsen"
  email = "Ingrid.s.96@hotmail.com"
  image = "https://avatars.githubusercontent.com/u/124798153?s=400&u=e2dbc7ded4ac6e9d3a0deaf1d8bb0fe24b6ea32a&v=4"
  imageQuality = 96
  headline = "Building systems, exploring ideas, and improving through code."
  bio = "Welcome to my webpage, a portfolio of projects, experiments, and lessons learned while studying Computer science .. loading next episode... 26% "
  links = [
{ email = "Ingrid.s.96@hotmail.com" },
#     { link = "https://link-to-some-website.com/" },
#    { discord = "https://discord.gg/invitecode" },
#     { facebook = "https://facebook.com/username" },
{ github = "https://github.com/Ingridksv" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { linkedin = "https://linkedin.com/in/username" },
#   ]
