[navbar]
  displayTitle = true
  displayLogo = false
  width = "normal"

[footer]
  enable = true
  displayCopyright = false
  displayPoweredBy = false

[search]
  enable = true
  type = "flexsearch"

[theme]
  default = "system"